#!/bin/sh
# check - Checks scripts with whatever checkers seem appropriate.
#
# This file is part of newrepo-findrepo, tools for small Git servers.
#
# Written in 2018, 2019 by Eliah Kagan <degeneracypressure@gmail.com>.
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

set -e

status=0

do_check() {
    checker="$1" path_to_check="$2"
    printf 'Checking %s with %s.\n' "$2" "$1"
    "$checker" -- "$path_to_check" || status="$?"
}

examine() {
    path="$1"

    case "$(file --mime-type -- "$1" | awk '{ print $2 }')" in
    text/x-shellscript)
        do_check shellcheck "$path"
        ;;

    text/x-python)
        do_check pylint3 "$path"
        do_check pycodestyle "$path"
    esac
}

for f in *; do
    if [ -f "$f" ] && [ -e "$f" ]; then
        examine "$f"
    fi
done

exit "$status"
