#!/bin/sh
# deploy - install newrepo and findrepo into /usr/local/bin
#
# This file is part of newrepo-findrepo, tools for small Git servers.
#
# Written in 2019 by Eliah Kagan <degeneracypressure@gmail.com>.
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

set -f

dest='/usr/local/bin'

if [ "$#" -ne 1 ]; then
    printf 'Usage: %s GROUP\n' "$0" >&2
    exit 3
fi

group="$1"

if [ "$(getent group "$group" | awk -F: '{ print $1 }')" -ne "$group" ]; then
    printf '%s: error: no "%s" group\n' "$0" "$group" >&2
    exit 2
fi

status=0

for cmd in newrepo findrepo; do
    install -g "$group" -m 750 "$cmd" "$dest/"
    last_status="$?"
    [ "$last_status" -eq 0 ] || [ "$status" -ne 0 ] || status="$last_status"
done

exit "$status"
