#!/bin/sh
# This utility run on the server, where it creates a new repo. Usage:
#    newrepo NAME

if [ -z "$1" ]; then
    printf 'What do you want to call the new repo?\n' >&2
    exit 1
fi

dir="$1.git"
url="ssh://team-roach.ddns.net/repos/$dir"

cd /repos && mkdir "$dir" && cd "$dir" && git init --bare &&
    printf '\nThe URL of the newly created repository is:\n\n\t%s\n' "$url"
